config/routes.rb
CookingWithKing::Application.routes.draw do
  root 'pages#home'
  get 'suggestions' => 'pages#suggestions'
  get 'suggest' => 'pages#suggestions'
  get 'test' => 'pages#test_episode'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="well infowell">
		<p>&copy; 2014 Kaptoye / <%= link_to "Suggest an item ", suggestions_path %></p>
</div>

app/views/layouts/_header.html.erb
<!-- Start of Header -->
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container"> <!-- Pull in Nav -->

<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  <div class="navbar-brand">
    <%= link_to "Cooking with King", root_path, class: "navbar-brand" %>

  </div>
</div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-links">
      <ul class="nav navbar-nav navbar-right">

          <li><%= link_to "Episodes", root_path %></li>
          <li><%= link_to "Suggestions", suggestions_path %></li>
          <li><%= link_to "Forums", "http://forums.athensmc.com" %></li>
          <li><%= link_to "YouTube", "http://youtube.com/user/kaptoye" %></li>

      </ul>
    </div><!-- /.navbar-collapse -->


  </div> <!-- End Container -->
</nav> <!-- End NavBar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title )%> / Cooking with King</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render 'layouts/header' %>

<div class="container">
<%= yield %>
<%= render 'layouts/footer' %>

</div>

</body>
</html>

app/views/pages/home.html.erb
<% content_for :title, "Welcome Home" %>
<div class="well">
  <div class="page-header">
    <h1>Welcome to CookingWithKing!</h1>
  </div>

  <p>
    Cooking with King is my quest to learn how to cook better food at home instead of eating out. I intend to cover all kinds of foods including breakfast, lunch, dinner and the most
    important meal: dessert. </p>

  <p>If you have a suggestion for a meal to make, check out the suggestions page for information on how to submit a suggestion.</p>
</div>

app/views/pages/suggestions.html.erb
<% content_for :title, "Suggestions" %>
<div class="well">
  <div class="page-header">
    <h1>Suggestions</h1>
  </div>
  <p>Got an idea of something you'd like to see King make on the show? Fill out the Google Form below!</p>

  <iframe src="https://docs.google.com/forms/d/1MqihgFQnsEXuMSwhuwWRiDSwk9ZtbKc4LZ4utjbQT8M/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>

app/views/pages/test_episode.html.erb
<% content_for :title, "Test Video Episode" %>
<div class="well">
  <div class="page-header">
    <h1>Testing of Video Editor/Player</h1>
  </div>
  <p>The following video is a test of a video player... avoiding YT if I can! :D</p>


	<div class="row">
		<div class="col-md-7">
      <iframe src="//fast.wistia.net/embed/iframe/ua8hsru9rv" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="360"></iframe>


		</div>
		<div class="col-md-5">
		<!--
		<img src="http://placehold.it/853x480">
		-->
			<div class="panel panel-info">
				<div class="panel-heading">
					<h5>More Episodes</h5>
				</div>
				<div class="panel-body">
					<ul class="nav nav-pills nav-stacked">
			   			<li><a href="#">Episode 0 - Series Introduction & How awesome I am</a></li>
			  			<li class="active"><a href="#">Episode 1 - Memory Lane</a></li>
			   			<li><a href="#">Episode 2 - Gold Farm Project</a></li>
			  			<li><a href="#">Episode 3 - Smoking the gun</a></li>
			  			<li><a href="#">Episode 4 - I'm #4 in the list</a></li>
			  			<li><a href="#">Episode 5 - I'm the last guy to show up here</a></li>
					</ul>
				</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
					  <div class="panel-body">
					  King is an awesome dude who just wants to make videos for ever and ever and ever and this is his site that he made and put a ton of work in. Does this make his content look fat? Just kidding we all know it's fat as heck. Ok you can go now. I just wanted to test out a 'Content Creators about section'
					  </div>
  					  <div class="panel-body">
  					  	<div class="pull-left">
							<img src="https://pbs.twimg.com/profile_images/2327720753/pncsl3exa97o8ako1y8u_bigger.png" class="img-rounded"/>
						</div>
						<strong>Kaptoye</strong>
						<small>1230 Videos</small>


							<div class="pull-right">
								<p class="bg-info">1 view</p>
							</div>

					  </div>

			</div>

		</div>  <!-- End 12 col. section -->
	</div> <!-- End Row -->



</div>